<?php
/**
 * Created by PhpStorm.
 * User: angelariasgonzalez
 * Date: 11/2/18
 * Time: 22:00
 */
namespace fw\Data\Type;
use fw\Data\Type;

class Photo extends Type
{
    public function __toString()
    {
        return "<img src='dss'>"; // TODO: Change the autogenerated stub
    }
}